name: story_time
description: A fork of story. Instagram stories like UI with rich animations and even more customizability than the original package.
version: 1.0.6
homepage: https://github.com/tjcampanella/story_time

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  cached_video_player: ^2.0.4
  flutter:
    sdk: flutter
  provider: ^6.0.3

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
